[project]
name = "jtttestserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "一只踩坑少年", email = "3067188237@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pyside6>=6.11.2",
]

[project.scripts]
jtttestserver = "jtttestserver:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
